server {
    listen 80;
    server_name localhost _;

    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    types {
        text/html                             html htm;
        text/css                              css;
        application/javascript                js mjs;
        application/json                      json;
        image/png                             png;
        image/jpeg                            jpg jpeg;
        image/svg+xml                         svg;
        image/x-icon                          ico;
        image/webp                            webp;
        font/woff2                            woff2;
        font/woff                             woff;
        font/ttf                              ttf;
    }

    # Gzip Compression
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied any;
    gzip_types text/plain text/css text/javascript application/javascript application/x-javascript application/json application/xml image/svg+xml;

    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Arquivos estáticos e Assets
    location ~* \.(?:css|js|png|jpg|jpeg|gif|ico|svg|webp|woff|woff2|ttf|eot)$ {
        expires 30d;
        access_log off;
        add_header Cache-Control "public, no-transform";
        try_files $uri =404;
    }

    # Roteamento de páginas
    location / {
        try_files $uri $uri.html $uri/ /index.html;
    }

    error_page 404 /index.html;
}
